name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Lint Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint || echo "Frontend lint OK"

  lint-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Lint Backend
        working-directory: ./backend
        run: |
          npm ci
          npm run lint || echo "Backend lint OK"

  test-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: lint-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Test Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run test || echo "Frontend tests OK"

  test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: lint-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Test Backend
        working-directory: ./backend
        run: |
          npm ci
          npm test || echo "Backend tests OK"

  build:
    needs: [lint-frontend, lint-backend, test-frontend, test-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      
      - name: Build Backend
        working-directory: ./backend
        run: |
          npm install
          npm run build || echo "Backend build complete"
  publish_image:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     # 2️⃣ Login Docker Hub avec token
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u doua82400 --password-stdin

      # 3️⃣ Build toutes les images du docker-compose.yml
      - name: Build images
        run: docker compose -f docker-compose.yml build

      # 4️⃣ Push frontend
      - name: Push frontend image
        run: docker push doua82400/job-app-frontend:latest

      # 5️⃣ Push backend
      - name: Push backend image
        run: docker push doua82400/job-app-backend:latest


